/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "DynamoTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DynamoTestTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "JWT_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
