export enum KeyEnum {
    USER = 'USER',
    EMAIL = 'EMAIL',
    USERNAME = 'USERNAME',
    AREA = 'AREA',
    PLACE = 'PLACE',
    PLACE_TYPE = 'PLACE_TYPE',
    CATEGORY = 'CATEGORY',
    CATEGORY_GROUP = 'CATEGORY_GROUP',
    METADATA = 'METADATA',
}